version: '3.3'
services:
    nginx:
        container_name: nginxd
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - '$PWD/nginx_proxy.conf:/etc/nginx/nginx.conf'
            - '$PWD/data/log/:/var/log/nginx/'
            - '$PWD/example.com-ssl.crt:/etc/ssl/certs/example.com-ssl.crt'
            - '$PWD/example.com-ssl.key:/etc/ssl/private/example.com-ssl.key'
        image: 'nginx:latest'