version: '2.0'
services:
    nginx:
        container_name: nginxd
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - './nginx_proxy.conf:/etc/nginx/nginx.conf'
            - './data/log/:/var/log/nginx/'
            - './example.com-ssl.crt:/etc/ssl/certs/example.com-ssl.crt'
            - './example.com-ssl.key:/etc/ssl/private/example.com-ssl.key'
        image: 'nginx:latest'